"""rapports narratifs

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-27 18:40:42.054017
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "narrative_reports",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("execution_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "submitted", "approved", name="report_status"),
            nullable=False,
        ),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("missing_information", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("indicator_suggestions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("review_comment", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("submitted_by", sa.Uuid(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
            name=op.f("fk_narrative_reports_approved_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_narrative_reports_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["activity_executions.id"],
            name=op.f("fk_narrative_reports_execution_id_activity_executions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_narrative_reports_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_narrative_reports_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by"],
            ["users.id"],
            name=op.f("fk_narrative_reports_submitted_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_narrative_reports")),
        sa.UniqueConstraint("execution_id", name=op.f("uq_narrative_reports_execution_id")),
    )
    op.create_index(
        op.f("ix_narrative_reports_organization_id"),
        "narrative_reports",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_narrative_reports_project_id"), "narrative_reports", ["project_id"], unique=False
    )
    op.create_table(
        "report_versions",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_report_versions_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_report_versions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["narrative_reports.id"],
            name=op.f("fk_report_versions_report_id_narrative_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_versions")),
        sa.UniqueConstraint("report_id", "version", name=op.f("uq_report_versions_report_id")),
    )
    op.create_index(
        op.f("ix_report_versions_organization_id"),
        "report_versions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_report_versions_report_id"), "report_versions", ["report_id"], unique=False
    )
    op.add_column("indicator_values", sa.Column("execution_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_indicator_values_execution_id"), "indicator_values", ["execution_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_indicator_values_execution_id_activity_executions"),
        "indicator_values",
        "activity_executions",
        ["execution_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_indicator_values_execution_id_activity_executions"),
        "indicator_values",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_indicator_values_execution_id"), table_name="indicator_values")
    op.drop_column("indicator_values", "execution_id")
    op.drop_index(op.f("ix_report_versions_report_id"), table_name="report_versions")
    op.drop_index(op.f("ix_report_versions_organization_id"), table_name="report_versions")
    op.drop_table("report_versions")
    op.drop_index(op.f("ix_narrative_reports_project_id"), table_name="narrative_reports")
    op.drop_index(op.f("ix_narrative_reports_organization_id"), table_name="narrative_reports")
    op.drop_table("narrative_reports")
    # ### end Alembic commands ###
    sa.Enum(name="report_status").drop(op.get_bind(), checkfirst=True)
