"""agregation et redevabilite

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-27 18:56:03.971826
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "periodic_reports",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("monthly", "quarterly", "annual", "donor", name="periodic_kind"),
            nullable=False,
        ),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "draft", "submitted", "approved", name="report_status", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("missing_information", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("review_comment", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("submitted_by", sa.Uuid(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
            name=op.f("fk_periodic_reports_approved_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_periodic_reports_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_periodic_reports_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_periodic_reports_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by"],
            ["users.id"],
            name=op.f("fk_periodic_reports_submitted_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_periodic_reports")),
    )
    op.create_index(
        op.f("ix_periodic_reports_organization_id"),
        "periodic_reports",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_periodic_reports_project_id"), "periodic_reports", ["project_id"], unique=False
    )
    op.create_table(
        "feedback_entries",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("reference", sa.String(length=20), nullable=False),
        sa.Column("received_on", sa.Date(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "hotline",
                "suggestion_box",
                "community_meeting",
                "field_visit",
                "sms",
                "email",
                "other",
                name="feedback_channel",
            ),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "information",
                "suggestion",
                "appreciation",
                "complaint",
                "fraud",
                "sexual_exploitation",
                "safety",
                "other",
                name="feedback_category",
            ),
            nullable=False,
        ),
        sa.Column("sensitive", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("location", sa.String(length=300), nullable=False),
        sa.Column("activity_id", sa.Uuid(), nullable=True),
        sa.Column("anonymous", sa.Boolean(), nullable=False),
        sa.Column("contact", sa.String(length=300), nullable=False),
        sa.Column(
            "status",
            sa.Enum("received", "in_progress", "responded", "closed", name="feedback_status"),
            nullable=False,
        ),
        sa.Column("assigned_to", sa.Uuid(), nullable=True),
        sa.Column("response", sa.Text(), nullable=False),
        sa.Column("responded_on", sa.Date(), nullable=True),
        sa.Column("closed_on", sa.Date(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("client_uuid", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["logframe_nodes.id"],
            name=op.f("fk_feedback_entries_activity_id_logframe_nodes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["users.id"],
            name=op.f("fk_feedback_entries_assigned_to_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_feedback_entries_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_feedback_entries_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_feedback_entries_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback_entries")),
        sa.UniqueConstraint("client_uuid", name=op.f("uq_feedback_entries_client_uuid")),
        sa.UniqueConstraint("project_id", "reference", name=op.f("uq_feedback_entries_project_id")),
    )
    op.create_index(
        op.f("ix_feedback_entries_organization_id"),
        "feedback_entries",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feedback_entries_project_id"), "feedback_entries", ["project_id"], unique=False
    )
    op.create_table(
        "periodic_report_versions",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_periodic_report_versions_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_periodic_report_versions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["periodic_reports.id"],
            name=op.f("fk_periodic_report_versions_report_id_periodic_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_periodic_report_versions")),
        sa.UniqueConstraint(
            "report_id", "version", name=op.f("uq_periodic_report_versions_report_id")
        ),
    )
    op.create_index(
        op.f("ix_periodic_report_versions_organization_id"),
        "periodic_report_versions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_periodic_report_versions_report_id"),
        "periodic_report_versions",
        ["report_id"],
        unique=False,
    )
    op.create_table(
        "lessons_learned",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("activity_id", sa.Uuid(), nullable=True),
        sa.Column("source_report_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["logframe_nodes.id"],
            name=op.f("fk_lessons_learned_activity_id_logframe_nodes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_lessons_learned_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_lessons_learned_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_lessons_learned_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_report_id"],
            ["narrative_reports.id"],
            name=op.f("fk_lessons_learned_source_report_id_narrative_reports"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lessons_learned")),
    )
    op.create_index(
        op.f("ix_lessons_learned_organization_id"),
        "lessons_learned",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lessons_learned_project_id"), "lessons_learned", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lessons_learned_project_id"), table_name="lessons_learned")
    op.drop_index(op.f("ix_lessons_learned_organization_id"), table_name="lessons_learned")
    op.drop_table("lessons_learned")
    op.drop_index(
        op.f("ix_periodic_report_versions_report_id"), table_name="periodic_report_versions"
    )
    op.drop_index(
        op.f("ix_periodic_report_versions_organization_id"), table_name="periodic_report_versions"
    )
    op.drop_table("periodic_report_versions")
    op.drop_index(op.f("ix_feedback_entries_project_id"), table_name="feedback_entries")
    op.drop_index(op.f("ix_feedback_entries_organization_id"), table_name="feedback_entries")
    op.drop_table("feedback_entries")
    op.drop_index(op.f("ix_periodic_reports_project_id"), table_name="periodic_reports")
    op.drop_index(op.f("ix_periodic_reports_organization_id"), table_name="periodic_reports")
    op.drop_table("periodic_reports")
    for name in ("periodic_kind", "feedback_channel", "feedback_category", "feedback_status"):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
