"""execution des activites et preuves

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-27 18:27:16.562581
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_executions",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("location", sa.String(length=300), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("participants", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.Enum("in_progress", "completed", name="execution_status"), nullable=False
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("client_uuid", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["logframe_nodes.id"],
            name=op.f("fk_activity_executions_activity_id_logframe_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_activity_executions_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_activity_executions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_activity_executions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_executions")),
        sa.UniqueConstraint("client_uuid", name=op.f("uq_activity_executions_client_uuid")),
    )
    op.create_index(
        op.f("ix_activity_executions_activity_id"),
        "activity_executions",
        ["activity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_executions_organization_id"),
        "activity_executions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_executions_project_id"),
        "activity_executions",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "evidence",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("execution_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("report", "minutes", "attendance", "photo", "other", name="evidence_kind"),
            nullable=False,
        ),
        sa.Column("filename", sa.String(length=300), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=300), nullable=False),
        sa.Column("thumbnail_key", sa.String(length=300), nullable=False),
        sa.Column("caption", sa.Text(), nullable=False),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("consent_given", sa.Boolean(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("uploaded_by", sa.Uuid(), nullable=True),
        sa.Column("client_uuid", sa.Uuid(), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["activity_executions.id"],
            name=op.f("fk_evidence_execution_id_activity_executions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_evidence_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_evidence_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
            name=op.f("fk_evidence_uploaded_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
        sa.UniqueConstraint("client_uuid", name=op.f("uq_evidence_client_uuid")),
    )
    op.create_index(op.f("ix_evidence_execution_id"), "evidence", ["execution_id"], unique=False)
    op.create_index(
        op.f("ix_evidence_organization_id"), "evidence", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_evidence_project_id"), "evidence", ["project_id"], unique=False)
    op.add_column("expenses", sa.Column("execution_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_expenses_execution_id"), "expenses", ["execution_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_expenses_execution_id_activity_executions"),
        "expenses",
        "activity_executions",
        ["execution_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_expenses_execution_id_activity_executions"), "expenses", type_="foreignkey"
    )
    op.drop_index(op.f("ix_expenses_execution_id"), table_name="expenses")
    op.drop_column("expenses", "execution_id")
    op.drop_index(op.f("ix_evidence_project_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_organization_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_execution_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_activity_executions_project_id"), table_name="activity_executions")
    op.drop_index(op.f("ix_activity_executions_organization_id"), table_name="activity_executions")
    op.drop_index(op.f("ix_activity_executions_activity_id"), table_name="activity_executions")
    op.drop_table("activity_executions")
    # ### end Alembic commands ###
    for name in ("evidence_kind", "execution_status"):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
