"""projets cadre logique budget indicateurs

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-27 17:44:43.830638
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("donor", sa.String(length=200), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column(
            "status", sa.Enum("draft", "active", "closed", name="project_status"), nullable=False
        ),
        sa.Column("zones", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("target_groups", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_projects_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("organization_id", "code", name=op.f("uq_projects_organization_id")),
    )
    op.create_index(
        op.f("ix_projects_organization_id"), "projects", ["organization_id"], unique=False
    )
    op.create_table(
        "logframe_nodes",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column(
            "level",
            sa.Enum("goal", "outcome", "output", "activity", "sub_activity", name="node_level"),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("assumptions", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_logframe_nodes_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["logframe_nodes.id"],
            name=op.f("fk_logframe_nodes_parent_id_logframe_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_logframe_nodes_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_logframe_nodes")),
    )
    op.create_index(
        op.f("ix_logframe_nodes_organization_id"),
        "logframe_nodes",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_logframe_nodes_parent_id"), "logframe_nodes", ["parent_id"], unique=False
    )
    op.create_index(
        op.f("ix_logframe_nodes_project_id"), "logframe_nodes", ["project_id"], unique=False
    )
    op.create_table(
        "budget_lines",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("activity_id", sa.Uuid(), nullable=True),
        sa.Column("label", sa.String(length=300), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("donor_line_code", sa.String(length=40), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("frequency", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("is_estimate", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["logframe_nodes.id"],
            name=op.f("fk_budget_lines_activity_id_logframe_nodes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_budget_lines_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_budget_lines_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budget_lines")),
    )
    op.create_index(
        op.f("ix_budget_lines_activity_id"), "budget_lines", ["activity_id"], unique=False
    )
    op.create_index(
        op.f("ix_budget_lines_organization_id"), "budget_lines", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_budget_lines_project_id"), "budget_lines", ["project_id"], unique=False
    )
    op.create_table(
        "indicators",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("baseline", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("target", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("aggregation", sa.Enum("sum", "latest", name="aggregation"), nullable=False),
        sa.Column("disaggregations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_of_verification", sa.Text(), nullable=False),
        sa.Column("collection_method", sa.Text(), nullable=False),
        sa.Column("frequency", sa.String(length=40), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["logframe_nodes.id"],
            name=op.f("fk_indicators_node_id_logframe_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_indicators_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_indicators_owner_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_indicators_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_indicators")),
    )
    op.create_index(op.f("ix_indicators_node_id"), "indicators", ["node_id"], unique=False)
    op.create_index(
        op.f("ix_indicators_organization_id"), "indicators", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_indicators_project_id"), "indicators", ["project_id"], unique=False)
    op.create_table(
        "expenses",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("budget_line_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("spent_on", sa.Date(), nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["budget_line_id"],
            ["budget_lines.id"],
            name=op.f("fk_expenses_budget_line_id_budget_lines"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_expenses_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expenses")),
    )
    op.create_index(
        op.f("ix_expenses_budget_line_id"), "expenses", ["budget_line_id"], unique=False
    )
    op.create_index(
        op.f("ix_expenses_organization_id"), "expenses", ["organization_id"], unique=False
    )
    op.create_table(
        "indicator_values",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("indicator_id", sa.Uuid(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("value", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("disaggregation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("recorded_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["indicator_id"],
            ["indicators.id"],
            name=op.f("fk_indicator_values_indicator_id_indicators"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_indicator_values_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"],
            ["users.id"],
            name=op.f("fk_indicator_values_recorded_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_indicator_values")),
    )
    op.create_index(
        op.f("ix_indicator_values_indicator_id"), "indicator_values", ["indicator_id"], unique=False
    )
    op.create_index(
        op.f("ix_indicator_values_organization_id"),
        "indicator_values",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_indicator_values_organization_id"), table_name="indicator_values")
    op.drop_index(op.f("ix_indicator_values_indicator_id"), table_name="indicator_values")
    op.drop_table("indicator_values")
    op.drop_index(op.f("ix_expenses_organization_id"), table_name="expenses")
    op.drop_index(op.f("ix_expenses_budget_line_id"), table_name="expenses")
    op.drop_table("expenses")
    op.drop_index(op.f("ix_indicators_project_id"), table_name="indicators")
    op.drop_index(op.f("ix_indicators_organization_id"), table_name="indicators")
    op.drop_index(op.f("ix_indicators_node_id"), table_name="indicators")
    op.drop_table("indicators")
    op.drop_index(op.f("ix_budget_lines_project_id"), table_name="budget_lines")
    op.drop_index(op.f("ix_budget_lines_organization_id"), table_name="budget_lines")
    op.drop_index(op.f("ix_budget_lines_activity_id"), table_name="budget_lines")
    op.drop_table("budget_lines")
    op.drop_index(op.f("ix_logframe_nodes_project_id"), table_name="logframe_nodes")
    op.drop_index(op.f("ix_logframe_nodes_parent_id"), table_name="logframe_nodes")
    op.drop_index(op.f("ix_logframe_nodes_organization_id"), table_name="logframe_nodes")
    op.drop_table("logframe_nodes")
    op.drop_index(op.f("ix_projects_organization_id"), table_name="projects")
    op.drop_table("projects")
    for name in ("aggregation", "node_level", "project_status"):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
