"""formulaires de collecte

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-27 20:31:34.764772
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.core import rls

revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection_forms",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("activity_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["logframe_nodes.id"],
            name=op.f("fk_collection_forms_activity_id_logframe_nodes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_collection_forms_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_collection_forms_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_collection_forms_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collection_forms")),
    )
    op.create_index(
        op.f("ix_collection_forms_organization_id"),
        "collection_forms",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collection_forms_project_id"), "collection_forms", ["project_id"], unique=False
    )
    op.create_table(
        "form_submissions",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("form_id", sa.Uuid(), nullable=False),
        sa.Column("answers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("location", sa.String(length=300), nullable=False),
        sa.Column("latitude", sa.Double(), nullable=True),
        sa.Column("longitude", sa.Double(), nullable=True),
        sa.Column(
            "collected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("client_uuid", sa.Uuid(), nullable=True),
        sa.Column("submitted_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["form_id"],
            ["collection_forms.id"],
            name=op.f("fk_form_submissions_form_id_collection_forms"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_form_submissions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_form_submissions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by"],
            ["users.id"],
            name=op.f("fk_form_submissions_submitted_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form_submissions")),
        sa.UniqueConstraint("client_uuid", name=op.f("uq_form_submissions_client_uuid")),
    )
    op.create_index(
        op.f("ix_form_submissions_form_id"), "form_submissions", ["form_id"], unique=False
    )
    op.create_index(
        op.f("ix_form_submissions_organization_id"),
        "form_submissions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_form_submissions_project_id"), "form_submissions", ["project_id"], unique=False
    )
    for table in ("collection_forms", "form_submissions"):
        for statement in rls.enable_statements(table):
            op.execute(statement)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_form_submissions_project_id"), table_name="form_submissions")
    op.drop_index(op.f("ix_form_submissions_organization_id"), table_name="form_submissions")
    op.drop_index(op.f("ix_form_submissions_form_id"), table_name="form_submissions")
    op.drop_table("form_submissions")
    op.drop_index(op.f("ix_collection_forms_project_id"), table_name="collection_forms")
    op.drop_index(op.f("ix_collection_forms_organization_id"), table_name="collection_forms")
    op.drop_table("collection_forms")
    # ### end Alembic commands ###
