"""modeles de documents

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-27 20:14:04.306746
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.core import rls

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_templates",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("donor", sa.String(length=200), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("layout", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_document_templates_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_document_templates_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_templates")),
    )
    op.create_index(
        op.f("ix_document_templates_organization_id"),
        "document_templates",
        ["organization_id"],
        unique=False,
    )
    for statement in rls.enable_statements("document_templates"):
        op.execute(statement)
    op.add_column("narrative_reports", sa.Column("template_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_narrative_reports_template_id_document_templates"),
        "narrative_reports",
        "document_templates",
        ["template_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("periodic_reports", sa.Column("template_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_periodic_reports_template_id_document_templates"),
        "periodic_reports",
        "document_templates",
        ["template_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("terms_of_reference", sa.Column("template_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_terms_of_reference_template_id_document_templates"),
        "terms_of_reference",
        "document_templates",
        ["template_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_terms_of_reference_template_id_document_templates"),
        "terms_of_reference",
        type_="foreignkey",
    )
    op.drop_column("terms_of_reference", "template_id")
    op.drop_constraint(
        op.f("fk_periodic_reports_template_id_document_templates"),
        "periodic_reports",
        type_="foreignkey",
    )
    op.drop_column("periodic_reports", "template_id")
    op.drop_constraint(
        op.f("fk_narrative_reports_template_id_document_templates"),
        "narrative_reports",
        type_="foreignkey",
    )
    op.drop_column("narrative_reports", "template_id")
    op.drop_index(op.f("ix_document_templates_organization_id"), table_name="document_templates")
    op.drop_table("document_templates")
    # ### end Alembic commands ###
