"""termes de reference

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-27 18:16:08.307928
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "terms_of_reference",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column(
            "status", sa.Enum("draft", "submitted", "approved", name="tor_status"), nullable=False
        ),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("missing_information", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("review_comment", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("submitted_by", sa.Uuid(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["logframe_nodes.id"],
            name=op.f("fk_terms_of_reference_activity_id_logframe_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
            name=op.f("fk_terms_of_reference_approved_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_terms_of_reference_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_terms_of_reference_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_terms_of_reference_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by"],
            ["users.id"],
            name=op.f("fk_terms_of_reference_submitted_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_terms_of_reference")),
        sa.UniqueConstraint("activity_id", name=op.f("uq_terms_of_reference_activity_id")),
    )
    op.create_index(
        op.f("ix_terms_of_reference_organization_id"),
        "terms_of_reference",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_terms_of_reference_project_id"), "terms_of_reference", ["project_id"], unique=False
    )
    op.create_table(
        "tor_versions",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("tor_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_tor_versions_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_tor_versions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tor_id"],
            ["terms_of_reference.id"],
            name=op.f("fk_tor_versions_tor_id_terms_of_reference"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tor_versions")),
        sa.UniqueConstraint("tor_id", "version", name=op.f("uq_tor_versions_tor_id")),
    )
    op.create_index(
        op.f("ix_tor_versions_organization_id"), "tor_versions", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_tor_versions_tor_id"), "tor_versions", ["tor_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tor_versions_tor_id"), table_name="tor_versions")
    op.drop_index(op.f("ix_tor_versions_organization_id"), table_name="tor_versions")
    op.drop_table("tor_versions")
    op.drop_index(op.f("ix_terms_of_reference_project_id"), table_name="terms_of_reference")
    op.drop_index(op.f("ix_terms_of_reference_organization_id"), table_name="terms_of_reference")
    op.drop_table("terms_of_reference")
    # ### end Alembic commands ###
    sa.Enum(name="tor_status").drop(op.get_bind(), checkfirst=True)
